name = "ucloud"
main = "src/worker.ts"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB"
database_name = "ucloud"
database_id = "aa074fd0-e44b-453a-ace9-a912ef11c73e"

[observability.logs]
enabled = true