name = "ucloud"
main = "src/worker.ts"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB"
database_name = "ucloud"
database_id = "4e1f3e06-9109-4b5e-96ba-db63a47cc4e3"

[observability.logs]
enabled = true